services:
  ai-writing:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: '32gb'
    environment:
      - OMP_NUM_THREADS=16
      - TERM=xterm-256color
    env_file:
      - .local.env
    container_name: ai-writing
    working_dir: /workspace
    volumes:
      - source: ./
        target: /workspace
        type: bind
    tty: true
